### ISSUE TITLE
Social Media Buttons?

### ISSUE THREAD

**Issue by jzb** [projectatomic/atomic-site#117]
We should probably try to add social media buttons so people can easily tweet, share on Facebook, etc. 

Adding tigert to the ticket for discussion. IIRC there are some ways to do this, but some of them involve some objectionable JS.

**Comment by znmeb** [comment]
Social media share buttons are a two-edged sword. Yes, they make it easy to share a page. But

1. They don't have any effect on motivating people to share your content. That responsibility is the writer's.
2. They often add insane amounts of tracking traffic to servers and slow page loads to an unacceptable level.

I've pretty much decided to stop using them on my blog posts / pages. I still have Clicky Analytics on my pages because Google Analytics is a jargon-filled morass of nonsense, but that's where I'm drawing the line.

**Comment by jzb** [comment]
@tigert Pinging on this. Thanks!

**Comment by tigert** [comment]
Sorry I missed this initially, I guess github sends too much mail and I need to cut it down so I actually see relevant notifications.

Anyway, I created a pullrequest #218 that implements this, please test that it works correctly. I tried it locally and it seemed to work ok though.

**Comment by tigert** [comment]
I think we can close this, as the solution got merged.
